include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = OpenClawNC
OpenClawNC_FILES = OpenClawNCController.m
OpenClawNC_INSTALL_PATH = /System/Library/WeeAppPlugins
OpenClawNC_FRAMEWORKS = UIKit Foundation CoreGraphics QuartzCore
OpenClawNC_RESOURCE_DIRS = Resources
OpenClawNC_CFLAGS = -fno-objc-arc -Wno-deprecated-declarations

include $(THEOS_MAKE_PATH)/bundle.mk
