include $(THEOS)/makefiles/common.mk

TWEAK_NAME = OpenClawTweak
OpenClawTweak_FILES = Tweak.xm
OpenClawTweak_FRAMEWORKS = UIKit Foundation CoreGraphics QuartzCore Security
OpenClawTweak_CFLAGS = -Wno-deprecated-declarations -Wno-unused-variable -fno-objc-arc

include $(THEOS_MAKE_PATH)/tweak.mk
