include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = ClawPodNC
ClawPodNC_FILES = ClawPodNCController.m
ClawPodNC_INSTALL_PATH = /System/Library/WeeAppPlugins
ClawPodNC_FRAMEWORKS = UIKit Foundation CoreGraphics QuartzCore
ClawPodNC_RESOURCE_DIRS = Resources
ClawPodNC_CFLAGS = -fno-objc-arc -Wno-deprecated-declarations

include $(THEOS_MAKE_PATH)/bundle.mk
