include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = LegacyPodClawNC
LegacyPodClawNC_FILES = LegacyPodClawNCController.m
LegacyPodClawNC_INSTALL_PATH = /System/Library/WeeAppPlugins
LegacyPodClawNC_FRAMEWORKS = UIKit Foundation CoreGraphics QuartzCore
LegacyPodClawNC_RESOURCE_DIRS = Resources
LegacyPodClawNC_CFLAGS = -fno-objc-arc -Wno-deprecated-declarations

include $(THEOS_MAKE_PATH)/bundle.mk
