include $(THEOS)/makefiles/common.mk

TWEAK_NAME = ClawPodTweak
ClawPodTweak_FILES = Tweak.xm
ClawPodTweak_FRAMEWORKS = UIKit Foundation CoreGraphics QuartzCore Security
ClawPodTweak_CFLAGS = -Wno-deprecated-declarations -Wno-unused-variable -fno-objc-arc

include $(THEOS_MAKE_PATH)/tweak.mk
